# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4624ee0ec12d914042f63c5833fcbe562ed86d5ee6032ea31011002e6b44f14176d2b2c4f42586b46500291aa41a7443b74a80b3a2078277918dff965d063dd2

test:
  secret_key_base: 9f27cee18beebc8a0f82a7978f97060c092448d06e4a8b635f029005cebf19e92460c32d6d2474071f7296670287629cc7f83306f11a3986741ef3d7c71a5d79

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
